[mapper]
"Peptide Sequence" = "Sequence"
Protein = "Proteins"
"Modified Sequence" = "Modified sequence"
Charge = "Charge"

[replicate_mapper]
"A_1 Intensity" = 1
"A_2 Intensity" = 1
"A_3 Intensity" = 1
"B_1 Intensity" = 2
"B_2 Intensity" = 2
"B_3 Intensity" = 2

[run_mapper]
"A_1 Intensity" = "LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01"
"A_2 Intensity" = "LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02"
"A_3 Intensity" = "LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03"
"B_1 Intensity" = "LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01"
"B_2 Intensity" = "LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02"
"B_3 Intensity" = "LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03"


[species_dict]
"YEAST" = "_YEAST"
"ECOLI" = "_ECOLI"
"HUMAN" = "_HUMAN"

[general]
contaminant_flag = "Cont_"
decoy_flag = false
