[mapper]
"proteins" = "Proteins"
"peptide" = "Sequence"
"charge" = "Charge"

[replicate_mapper]
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01.mzML.gz" = 1
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02.mzML.gz" = 1
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03.mzML.gz" = 1
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01.mzML.gz" = 2
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02.mzML.gz" = 2
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03.mzML.gz" = 2

[run_mapper]
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01.mzML" = "LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02.mzML" = "LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03.mzML" = "LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01.mzML" = "LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02.mzML" = "LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03.mzML" = "LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03"

[species_dict]
"YEAST" = "_YEAST"
"ECOLI" = "_ECOLI"
"HUMAN" = "_HUMAN"

[general]
contaminant_flag = "Cont_"
decoy_flag = false
