[mapper]
"Peptide Sequence" = "Sequence"
Protein = "Proteins"
"Modified Sequence" = "Modified sequence"
Charge = "Charge"

[replicate_mapper]
"A_1 Intensity" = 1
"A_2 Intensity" = 1
"A_3 Intensity" = 1
"B_1 Intensity" = 2
"B_2 Intensity" = 2
"B_3 Intensity" = 2

[run_mapper]
"A_1 Intensity" = "Condition_A_Sample_Alpha_01"
"A_2 Intensity" = "Condition_A_Sample_Alpha_02"
"A_3 Intensity" = "Condition_A_Sample_Alpha_03"
"B_1 Intensity" = "Condition_B_Sample_Alpha_01"
"B_2 Intensity" = "Condition_B_Sample_Alpha_02"
"B_3 Intensity" = "Condition_B_Sample_Alpha_03"


[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[species_expected_ratio]
[species_expected_ratio.YEAST]
"1|2" = 2.0

[species_expected_ratio.ECOLI]
"1|2" = 0.25
    
[species_expected_ratio.HUMAN]
"1|2" = 1.0

[general]
contaminant_flag = "Cont_"
decoy_flag = false
min_count_multispec = 1