[mapper]
"Peptide Sequence" = "Sequence"
Protein = "Proteins"
"Modified Sequence" = "Modified sequence"
Charge = "Charge"

[replicate_mapper]
"A_1 Intensity" = "A"
"A_2 Intensity" = "A"
"A_3 Intensity" = "A"
"B_1 Intensity" = "B"
"B_2 Intensity" = "B"
"B_3 Intensity" = "B"

[run_mapper]
"A_1 Intensity" = "Condition_A_Sample_Alpha_01"
"A_2 Intensity" = "Condition_A_Sample_Alpha_02"
"A_3 Intensity" = "Condition_A_Sample_Alpha_03"
"B_1 Intensity" = "Condition_B_Sample_Alpha_01"
"B_2 Intensity" = "Condition_B_Sample_Alpha_02"
"B_3 Intensity" = "Condition_B_Sample_Alpha_03"


[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[general]
contaminant_flag = "Cont_"
decoy_flag = false
