[mapper]
"Proteins" = "Proteins"
Sequence = "Sequence"
Charge = "Charge"


[replicate_mapper]
LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01 = 1
LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02 = 1
LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03 = 1
LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01 = 2
LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02 = 2
LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03 = 2

[run_mapper]
LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01 = "Condition_A_Sample_Alpha_01"
LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02 = "Condition_A_Sample_Alpha_02"
LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03 = "Condition_A_Sample_Alpha_03"
LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01 = "Condition_B_Sample_Alpha_01"
LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02 = "Condition_B_Sample_Alpha_02"
LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03 = "Condition_B_Sample_Alpha_03"

[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[species_expected_ratio]
[species_expected_ratio.YEAST]
"1|2" = 0.5

[species_expected_ratio.ECOLI]
"1|2" = 1.5
    
[species_expected_ratio.HUMAN]
"1|2" = 1.0

[general]
contaminant_flag = "Cont_"
decoy_flag = true
min_count_multispec = 1