[project]
name = "proteobench"
authors = [
    { name = "Robbin Bouwmeester", email = "robbin.bouwmeester@ugent.be" },
] # TODO: Add others
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Development Status :: 4 - Beta",
]
keywords = ['proteomics', 'peptides', 'retention time', 'mass spectrometry']
requires-python = ">=3.7"
dynamic = ["version", "description"]
dependencies = [
    "pandas",
    "numpy",
    "plotly",
    "streamlit_extras",
    "streamlit-plotly-events",
    "matplotlib",
    "importlib-metadata; python_version < '3.8'",
    "toml",
]

[project.optional-dependencies]
dev = ["black"]
docs = ["sphinx", "sphinx-rtd-theme", "sphinx-autobuild", "myst-parser"]
web = ["streamlit", "scipy"]

[project.urls]
"Homepage" = "https://github.com/ProteoBench"
"Bug Tracker" = "https://github.com/ProteoBench/ProteoBench/issues/"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
