[project]
authors = [
  {name = "Robbin Bouwmeester", email = "robbin.bouwmeester@ugent.be"},
] # TODO: Add others
classifiers = [
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
  "Development Status :: 4 - Beta",
]
dependencies = [
  "pandas",
  "numpy",
  "plotly",
  "streamlit_extras",
  "streamlit-plotly-events",
  "matplotlib",
  "importlib-metadata; python_version < '3.8'",
  "toml",
]
dynamic = ["version", "description"]
keywords = ['proteomics', 'peptides', 'retention time', 'mass spectrometry']
license = {file = "LICENSE"}
name = "proteobench"
readme = "README.md"
requires-python = ">=3.7"

[project.optional-dependencies]
dev = ["black"]
docs = ["sphinx", "sphinx-rtd-theme", "sphinx-autobuild", "myst-parser"]
web = ["streamlit>1.27", "scipy"]

[project.urls]
"Bug Tracker" = "https://github.com/ProteoBench/ProteoBench/issues/"
"Homepage" = "https://github.com/ProteoBench"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[tool.flake8]
max-line-length = 120
