[mapper]
"Sequence" = "Sequence"
Proteins = "Proteins"
"Intensity" = "Intensity_orig_file"

[condition_mapper]
"Intensity A_Sample_Alpha_01" = "A"
"Intensity A_Sample_Alpha_02" = "A"
"Intensity A_Sample_Alpha_03" = "A"
"Intensity B_Sample_Alpha_01" = "B"
"Intensity B_Sample_Alpha_02" = "B"
"Intensity B_Sample_Alpha_03" = "B"

[run_mapper]
"Intensity A_Sample_Alpha_01" = "Condition_A_Sample_Alpha_01"
"Intensity A_Sample_Alpha_02" = "Condition_A_Sample_Alpha_02"
"Intensity A_Sample_Alpha_03" = "Condition_A_Sample_Alpha_03"
"Intensity B_Sample_Alpha_01" = "Condition_B_Sample_Alpha_01"
"Intensity B_Sample_Alpha_02" = "Condition_B_Sample_Alpha_02"
"Intensity B_Sample_Alpha_03" = "Condition_B_Sample_Alpha_03"

[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[general]
contaminant_flag = "Cont_"
decoy_flag = true
