[[pages]]
path = "Home.py"
name = "Home"

[[pages]]
path = "pages/Quant/DDA/ion.py"
name = "DDA Quant Ion Level -BETA-"

[[pages]]
path = "pages/Quant/DDA/peptidoform.py"
name = "DDA Quant Peptidoform Level -BETA-"

[[pages]]
path = "pages/Quant/DIA/ion_AIF.py"
name = "DIA Quant Ion Level - AIF -BETA-"

[[pages]]
path = "pages/Quant/DIA/ion_diaPASEF.py"
name = "DIA Quant Ion Level - diaPASEF -BETA-"