[mapper]
"Modified.Sequence" = "Sequence"
"File.Name" = "Raw file"
"Protein.Names" = "Proteins"
"proforma" = "proforma"
"Precursor.Charge" = "Charge"
"Precursor.Quantity" = "Intensity"

[condition_mapper]
"LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.raw" = "A"
"LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.raw" = "A"
"LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.raw" = "A"
"LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.raw" = "B"
"LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.raw" = "B"
"LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.raw" = "B"

[run_mapper]
"LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.raw" = "Condition_A_Sample_Alpha_01"
"LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.raw" = "Condition_A_Sample_Alpha_02"
"LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.raw" = "Condition_A_Sample_Alpha_03"
"LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.raw" = "Condition_B_Sample_Alpha_01"
"LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.raw" = "Condition_B_Sample_Alpha_02"
"LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.raw" = "Condition_B_Sample_Alpha_03"

[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[general]
contaminant_flag = "Cont_"
decoy_flag = true
