name: Automated Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --local user.name "Your Name"
        git config --local user.email "your-email@example.com"

    - name: Automatic Tagging
      id: tag_version
      uses: "anothrNick/github-tag-action@1.36.0"
      with:
        default_bump: patch
        release_branches: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      if: steps.tag_version.outputs.new_tag != ''
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: 'New release'
        draft: false
        prerelease: false
