name: Automated Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build wheel
      run: |
        python -m build --wheel

    - name: Upload wheel to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*.whl

    - name: Create GitHub Release
      uses: docker://antonyurchenko/git-release:v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
      with:
        args: |
          dist/*.whl
