name: Automated Release

on:
  push:
    tags:
      - 'v*'

jobs:
  git-release:
    runs-on: ubuntu-latest
    steps:
    - name: Download installer
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - name: Create GitHub Release
      uses: docker://antonyurchenko/git-release:v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
      with:
        args: |
          dist/*
